DROP TABLE IF EXISTS `default`.KDN_RETAILER_INDUSTRY;
  
CREATE TABLE `default`.KDN_RETAILER_INDUSTRY
(
    RETAILER_ID BIGINT
    ,INDUSTRY INT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE
tblproperties('skip.header.line.count'='1');