DROP TABLE IF EXISTS `default`.KDN_PRODUCTS;
  
CREATE TABLE `default`.KDN_PRODUCTS
(
    RETAILER_ID BIGINT
    ,BARCODE STRING
    ,QUANTITY DECIMAL(18,5)
    ,REVENUE DECIMAL(18,5)
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE
tblproperties('skip.header.line.count'='1'); 