DROP TABLE IF EXISTS `default`.KDN_PRODUCT_SUGGESTION_SALE_SPEED;
  
CREATE TABLE `default`.KDN_PRODUCT_SUGGESTION_SALE_SPEED
(
    BUSINESS_DATE STRING
    ,RETAILER_ID BIGINT
    ,PRODUCT_ID BIGINT
    ,BARCODE STRING
    ,DAILY_SALE_30 DECIMAL(18,5)
    ,DAILY_SALE_20 DECIMAL(18,5)
    ,DAILY_SALE_15 DECIMAL(18,5)
    ,DAILY_SALE_10 DECIMAL(18,5)
    ,DAILY_SALE_5 DECIMAL(18,5)
    ,DAILY_SALE_1 DECIMAL(18,5) 
    ,QUANTITY_30_DAYS DECIMAL(18,5)
    ,REVENUE_30_DAYS DECIMAL(18,5)
    ,ENDING_STOCKS DECIMAL(18,5)
    ,INVOICE_FROM BIGINT
    ,PREDICT_7 DECIMAL(18,5)
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE
tblproperties('skip.header.line.count'='1');